### PR TITLE
Add support for blade

### PR DESCRIPTION
**Pull request by adriaanzon**
Add support for Laravel's templating engine Blade. For use with the blade syntax plugin: https://github.com/jwalton512/vim-blade

### CODE REVIEW

**Comment by adriaanzon** [comment]
Changed the pattern to ignore short `@section` statements

**Comment by adriaanzon** [comment]
I'll close this since there are already 6 new blade directives since I opened this pull request. It will become a pain to keep up to date.

**Comment by tpope** [comment]
FWIW there's no reason you can't stick all this in a separate plugin and update as often as you like.

**Comment by adriaanzon** [comment]
Yeah I was planning to add them to vim-blade

**Pull request closed without merging**
