### PR TITLE
[Vim] fix syngroups, add 'end_pattern'

### LINKED ISSUE #96: False positives for outermost block of nested structures
Given the following vimscript example, where `|` represents the cursor:

```vim
function Foo()|
  if 1
  endif
endfunction
```

when you press `<CR>`, you'll get a false positive.

```vim
function Foo()
  |
endfunction
  if 1
  endif
endfunction
```

This `sh` example also produces a false positive:

```sh
if true; then|
  for item in a b c; do
  done
fi
```

It only seems to happen in filetypes that have an `endwise_addition` that starts with `\=`. When I bring the `endwise_addition` of `vim` down to "end&", it doesn't happen anymore.

### PR DESCRIPTION
**Pull request by Synray**
Attempts to fix #96, backwards compatible.

### CODE REVIEW

**Comment by tpope** [comment]
Don't rename `b:endwise_pattern`, it's a public interface.

**Comment by Abominas** [comment]
Reverted.

PS -- For the majority of commits I've made on this branch I've used vim-fugitive. Great plugin.

**Comment by Synray** [comment]
I dropped the 'revert' and the 'change variable name' commits with `git rebase -i` like you recommended in the style guide.

**Comment by tpope** [comment]
Change `endpat` to `end_pattern` please.

**Comment by Synray** [comment]
Done, rebased again.

**Pull request merged**
